[root]
cert = "../certs/root/cert/root.cer"
key = "../certs/root/private/root.key"
chain = ""

[issuing]
cert = "../certs/issuing/cert/issuing.cer"
key = "../certs/issuing/private/issuing.key"
chain = "../certs/issuing/cert/cacerts.cer"

[server]
cert = "../certs/server/server.cer"
key = "../certs/server/server.key"
chain = "../certs/server/cacerts.cer"

[client]
cert = "../certs/client/client.cer"
key = "../certs/client/client.key"
chain = "../certs/client/cacerts.cer"
